"""The design system: fonts self-hosted with the right type, the styleguide served, the
sample data generated from fixtures, and every JavaScript module at least parseable."""

from __future__ import annotations

import json
import re
import shutil
import subprocess

import pytest
from fastapi.testclient import TestClient

from app.config import PROJECT_ROOT, STATIC_DIR

FONTS = ["Barlow-400", "Barlow-500", "Barlow-600", "Barlow-700", "BarlowCondensed-500", "BarlowCondensed-600", "BarlowCondensed-700"]


def test_fonts_are_self_hosted_with_the_right_type(plain_client: TestClient):
    for name in FONTS:
        response = plain_client.get(f"/static/fonts/{name}.woff2", follow_redirects=False)
        assert response.status_code == 200, name
        assert response.headers["content-type"].startswith("font/woff2"), name
        assert response.content[:4] == b"wOF2", name
    assert (STATIC_DIR / "fonts" / "OFL.txt").exists()


def test_static_cache_headers(client: TestClient):
    assert client.get("/static/js/ui/dom.js").headers["cache-control"] == "no-cache"
    assert client.get("/static/css/tokens.css").headers["cache-control"] == "no-cache"
    assert client.get("/static/fonts/Barlow-400.woff2").headers["cache-control"] == "public, max-age=31536000, immutable"
    assert client.get("/").headers["cache-control"] == "no-cache"


def test_tokens_define_the_locked_palette_and_fonts():
    css = (STATIC_DIR / "css" / "tokens.css").read_text(encoding="utf-8")
    for token in ("--ground", "--panel", "--rule", "--chalk", "--fog", "--team-accent", "--team-primary", "--opp", "--good", "--stale", "--bad", "--replay"):
        assert f"{token}:" in css, token
    assert css.count("@font-face") == 7
    assert "../fonts/Barlow-400.woff2" in css
    assert "tabular-nums" in css
    assert "fonts.googleapis" not in css and "cdn" not in css.lower()


def test_no_third_party_urls_in_stylesheets_or_pages():
    for path in list((STATIC_DIR / "css").glob("*.css")) + list(STATIC_DIR.glob("*.html")):
        text = path.read_text(encoding="utf-8")
        assert "googleapis" not in text and "cdnjs" not in text and "unpkg" not in text, path.name


def test_styleguide_is_served_over_plain_http_and_https(plain_client: TestClient, client: TestClient):
    for test_client in (plain_client, client):
        response = test_client.get("/static/styleguide.html", follow_redirects=False)
        assert response.status_code == 200
        assert "/static/js/styleguide.js" in response.text
        assert "/static/css/components.css" in response.text


def test_sample_data_module_is_served_and_real(plain_client: TestClient):
    response = plain_client.get("/static/js/sample-data.js", follow_redirects=False)
    assert response.status_code == 200
    assert "javascript" in response.headers["content-type"]
    assert response.text.startswith("// Generated by tools/make_sample_data.py")
    body = response.text.split("export const sample = ", 1)[1].rstrip().rstrip(";")
    data = json.loads(body)
    assert data["team"]["school"] == "Swampwater Tech"
    assert data["record"]["overall"]["wins"] >= 0
    assert len(data["schedule"]) == 12
    assert data["live"]["home"]["school"] and data["live"]["away"]["school"]
    assert len(data["live"]["drives"]) > 10 and len(data["live"]["plays"]) > 100
    assert data["program"]["them"]["school"]
    assert len(data["roster"]) > 80
    assert data["profile"]["rows"][0]["nationalRank"] >= 1
    # 2026-09-21 additions: quarter scores, success rates, recruiting join, newspaper slate
    assert len(data["live"]["lineScores"]["home"]) >= 4 and len(data["live"]["lineScores"]["away"]) >= 4
    for side in data["live"]["box"].values():
        assert 0 <= side["successRate"] <= 1 and side["successCounts"]["judged"] > 0
        assert side["drives"] >= 1 and side["explosive"]["twenty"] >= side["explosive"]["forty"]
    assert any(isinstance(play.get("success"), bool) for play in data["live"]["plays"])
    assert any(player.get("highSchool") and player.get("stars") for player in data["roster"])
    assert all("highSchool" in player and "stars" in player for player in data["roster"])
    assert len(data["recruiting"]["commits"]) >= 1 and set(data["recruiting"]["starCounts"]) == {"1", "2", "3", "4", "5"}
    assert data["newspaper"]["slate"][0]["isUs"] and data["newspaper"]["slate"][0]["home"]["school"]
    assert len(data["newspaper"]["slate"]) >= 5 and all(g["home"]["school"] and g["away"]["school"] for g in data["newspaper"]["slate"])
    assert any(len(rows) >= 2 for rows in data["rosterHistory"].values())
    assert set(data["profiles"]) >= {"Swampwater Tech", data["program"]["them"]["school"]}
    assert data["program"]["advanced"]["Swampwater Tech"]["offense"]["successRate"] > 0


def test_generator_rebuilds_the_same_module(tmp_path, monkeypatch):
    import tools.make_sample_data as generator

    monkeypatch.setattr(generator, "OUT", tmp_path / "sample-data.js")
    assert generator.main() == 0
    written = (tmp_path / "sample-data.js").read_text(encoding="utf-8")
    current = (STATIC_DIR / "js" / "sample-data.js").read_text(encoding="utf-8")
    assert written == current, "static/js/sample-data.js is out of date: run python tools/make_sample_data.py"


def test_status_page_uses_the_design_tokens(client: TestClient):
    page = client.get("/status").text
    assert "/static/css/tokens.css" in page and "/static/css/components.css" in page
    assert 'class="wordmark"' in page
    assert "brand-mark" not in page


@pytest.mark.skipif(shutil.which("node") is None, reason="node is not installed")
def test_every_javascript_module_parses(tmp_path):
    modules = sorted((STATIC_DIR / "js").rglob("*.js"))
    assert len(modules) >= 28
    for module in modules:
        target = tmp_path / (module.stem + ".mjs")
        target.write_text(module.read_text(encoding="utf-8"), encoding="utf-8")
        result = subprocess.run(["node", "--check", str(target)], capture_output=True, text=True, timeout=30)
        assert result.returncode == 0, f"{module.relative_to(PROJECT_ROOT)}: {result.stderr[:400]}"


def test_components_cover_the_design_doc_list():
    js = "\n".join(path.read_text(encoding="utf-8") for path in (STATIC_DIR / "js" / "ui").glob("*.js"))
    for name in (
        "statTable", "playerCard", "driveRow", "sparkline", "pill", "keyPlayBadge", "ticker", "delaySlider", "editorial", "availabilityTable", "cover", "strip", "shell", "band",
        # added 2026-09-21 from the screenshot brief
        "teamStatsTable", "quarterLine", "winProbabilityChart", "successRow", "playSuccess", "leadersGrid", "boxLeader", "remoteBar", "openSheet",
        "matchupCard", "weatherRow", "teamHeader", "tiles", "starStrip", "impactCard", "newsDigest", "slateList", "rankTone",
    ):
        assert re.search(rf"export function {name}\b", js), name
